2023-03-31 11:08:15,061 ERROR list index out of range
Traceback (most recent call last):
  File "C:\_PyPr\MCF_ARAM_dev\mcf_dev.py", line 37, in wrapper
    result = func(*args, **kwargs)
  File "C:\_PyPr\MCF_ARAM_dev\mcf_dev.py", line 364, in parsePoroGames
    result = PoroAPI.get_poro_games(red_champion=converted_champion, gamemode=event)
  File "C:\_PyPr\MCF_ARAM_dev\mcf_api.py", line 156, in get_poro_games
    ids = [int(str(ids.get('class')).split('-')[1]) for ids in game[0:5]]
  File "C:\_PyPr\MCF_ARAM_dev\mcf_api.py", line 156, in <listcomp>
    ids = [int(str(ids.get('class')).split('-')[1]) for ids in game[0:5]]
IndexError: list index out of range
2023-03-31 11:09:23,344 ERROR list index out of range
Traceback (most recent call last):
  File "C:\_PyPr\MCF_ARAM_dev\mcf_dev.py", line 37, in wrapper
    result = func(*args, **kwargs)
  File "C:\_PyPr\MCF_ARAM_dev\mcf_dev.py", line 364, in parsePoroGames
    result = PoroAPI.get_poro_games(red_champion=converted_champion, gamemode=event)
  File "C:\_PyPr\MCF_ARAM_dev\mcf_api.py", line 156, in get_poro_games
    ids = [int(str(ids.get('class')).split('-')[1]) for ids in game[0:5]]
  File "C:\_PyPr\MCF_ARAM_dev\mcf_api.py", line 156, in <listcomp>
    ids = [int(str(ids.get('class')).split('-')[1]) for ids in game[0:5]]
IndexError: list index out of range
2023-03-31 11:09:30,681 ERROR list index out of range
Traceback (most recent call last):
  File "C:\_PyPr\MCF_ARAM_dev\mcf_dev.py", line 37, in wrapper
    result = func(*args, **kwargs)
  File "C:\_PyPr\MCF_ARAM_dev\mcf_dev.py", line 364, in parsePoroGames
    result = PoroAPI.get_poro_games(red_champion=converted_champion, gamemode=event)
  File "C:\_PyPr\MCF_ARAM_dev\mcf_api.py", line 156, in get_poro_games
    ids = [int(str(ids.get('class')).split('-')[1]) for ids in game[0:5]]
  File "C:\_PyPr\MCF_ARAM_dev\mcf_api.py", line 156, in <listcomp>
    ids = [int(str(ids.get('class')).split('-')[1]) for ids in game[0:5]]
IndexError: list index out of range
2023-05-27 05:17:58,836 ERROR No module named 'mcf_build_dev'
Traceback (most recent call last):
  File "C:\_PyPr\MCF_ARAM\mcf_main.py", line 37, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\_PyPr\MCF_ARAM\mcf_main.py", line 371, in parseAramGames
    from modules.GamesOnline import parsing_aram_api
  File "C:\_PyPr\MCF_ARAM\modules\GamesOnline.py", line 9, in <module>
    from mcf_build_dev import REGIONS_TUPLE, ELO_SYMBOLS
ModuleNotFoundError: No module named 'mcf_build_dev'
2023-05-27 05:21:05,096 ERROR name 'sw_afters' is not defined
Traceback (most recent call last):
  File "C:\_PyPr\MCF_ARAM\mcf_main.py", line 37, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\_PyPr\MCF_ARAM\mcf_main.py", line 578, in runMainParser
    showMainInfo(text='Searching..')
  File "C:\_PyPr\MCF_ARAM\mcf_main.py", line 194, in showMainInfo
    if sw_afters['info'][0] is not None:
       ^^^^^^^^^
NameError: name 'sw_afters' is not defined
2023-06-20 11:48:50,581 ERROR Short

2023-06-20 11:48:54,605 ERROR Short

2023-06-20 11:48:58,473 ERROR list index out of range

2023-06-20 11:49:06,740 ERROR list index out of range

2023-06-20 11:49:18,724 ERROR list index out of range
Traceback (most recent call last):
  File "C:\_PyPr\New_MCF\mcf_riot_api.py", line 43, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\_PyPr\New_MCF\mcf_riot_api.py", line 155, in get_poro_games
    ids = [int(str(ids.get('class')).split('-')[1]) for ids in game[0:5]]
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\_PyPr\New_MCF\mcf_riot_api.py", line 155, in <listcomp>
    ids = [int(str(ids.get('class')).split('-')[1]) for ids in game[0:5]]
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
2023-06-20 11:49:57,669 ERROR list index out of range
Traceback (most recent call last):
  File "C:\_PyPr\New_MCF\mcf_riot_api.py", line 43, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\_PyPr\New_MCF\mcf_riot_api.py", line 155, in get_poro_games
    ids = [int(str(ids.get('class')).split('-')[1]) for ids in game[0:5]]
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\_PyPr\New_MCF\mcf_riot_api.py", line 155, in <listcomp>
    ids = [int(str(ids.get('class')).split('-')[1]) for ids in game[0:5]]
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
2023-06-20 11:51:11,591 ERROR Short
Traceback (most recent call last):
  File "C:\_PyPr\New_MCF\mcf_riot_api.py", line 43, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\_PyPr\New_MCF\mcf_riot_api.py", line 111, in get_poro_games
    raise MCFException('Short')
mcf_build.MCFException: Short
2023-06-20 11:59:38,714 ERROR name 'ids' is not defined
Traceback (most recent call last):
  File "C:\_PyPr\New_MCF\mcf_riot_api.py", line 44, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\_PyPr\New_MCF\mcf_riot_api.py", line 158, in get_poro_games
    converted_ids = [ALL_CHAMPIONS_IDs.get(i) for i in ids]
                                                       ^^^
NameError: name 'ids' is not defined
2023-06-20 12:01:20,191 ERROR 'str' object has no attribute 'startwidth'
Traceback (most recent call last):
  File "C:\_PyPr\New_MCF\mcf_riot_api.py", line 44, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\_PyPr\New_MCF\mcf_riot_api.py", line 155, in get_poro_games
    if not game.get('class')[0].startwidth('champion'):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'startwidth'
2023-06-20 12:01:32,731 ERROR 'str' object has no attribute 'startwith'
Traceback (most recent call last):
  File "C:\_PyPr\New_MCF\mcf_riot_api.py", line 44, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\_PyPr\New_MCF\mcf_riot_api.py", line 155, in get_poro_games
    if not game.get('class')[0].startwith('champion'):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'startwith'
2023-06-20 12:02:54,180 ERROR ResultSet object has no attribute 'get'. You're probably treating a list of elements like a single element. Did you call find_all() when you meant to call find()?
Traceback (most recent call last):
  File "C:\_PyPr\New_MCF\mcf_riot_api.py", line 44, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\_PyPr\New_MCF\mcf_riot_api.py", line 156, in get_poro_games
    if not game.get('class')[0].startswith('champion'):
           ^^^^^^^^
  File "C:\_PyPr\New_MCF\.env\Lib\site-packages\bs4\element.py", line 2289, in __getattr__
    raise AttributeError(
AttributeError: ResultSet object has no attribute 'get'. You're probably treating a list of elements like a single element. Did you call find_all() when you meant to call find()?
2023-06-20 12:04:36,522 ERROR list index out of range
Traceback (most recent call last):
  File "C:\_PyPr\New_MCF\mcf_riot_api.py", line 44, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\_PyPr\New_MCF\mcf_riot_api.py", line 157, in get_poro_games
    if not champ.get('class')[0].startswith('champion'):
           ~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
2023-06-20 12:04:48,229 ERROR list index out of range
Traceback (most recent call last):
  File "C:\_PyPr\New_MCF\mcf_riot_api.py", line 44, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\_PyPr\New_MCF\mcf_riot_api.py", line 157, in get_poro_games
    if not champ.get('class')[0].startswith('champion'):
           ~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
2023-06-20 12:05:36,275 ERROR 'list' object has no attribute 'startswith'
Traceback (most recent call last):
  File "C:\_PyPr\New_MCF\mcf_riot_api.py", line 44, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\_PyPr\New_MCF\mcf_riot_api.py", line 157, in get_poro_games
    if not champ.get('class').startswith('champion'):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'startswith'
2023-06-20 12:05:46,286 ERROR list index out of range
Traceback (most recent call last):
  File "C:\_PyPr\New_MCF\mcf_riot_api.py", line 44, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\_PyPr\New_MCF\mcf_riot_api.py", line 157, in get_poro_games
    if not champ.get('class')[0].startswith('champion'):
           ~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
2023-06-20 12:08:51,949 ERROR Short
Traceback (most recent call last):
  File "C:\_PyPr\New_MCF\mcf_riot_api.py", line 44, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\_PyPr\New_MCF\mcf_riot_api.py", line 112, in get_poro_games
    raise MCFException('Short')
mcf_build.MCFException: Short
